// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    App1: typeof import('./src/components/App1.vue')['default']
    App2: typeof import('./src/components/App2.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Computed: typeof import('./src/components/Computed.vue')['default']
    Diyvue: typeof import('./src/components/Diyvue.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    Model: typeof import('./src/components/Model.vue')['default']
    Model1: typeof import('./src/components/Model1.vue')['default']
    MoveBox: typeof import('./src/components/MoveBox.vue')['default']
    NumberBox: typeof import('./src/components/NumberBox.vue')['default']
    Provide: typeof import('./src/components/Provide.vue')['default']
    Provide2: typeof import('./src/components/Provide2.vue')['default']
    Provide3: typeof import('./src/components/Provide3.vue')['default']
    Ref: typeof import('./src/components/Ref.vue')['default']
    Register: typeof import('./src/components/Register/index.vue')['default']
    Shop: typeof import('./src/components/Shop.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
    Watch: typeof import('./src/components/Watch.vue')['default']
    Zj1: typeof import('./src/components/Zj1.vue')['default']
  }
}

export {}
